name: List Members and Comment

on:
  workflow_dispatch:

jobs:
  list-members-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create summary
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}